server:
  port: 8080

spring:
  application:
    name: article
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/article?createDatabaseIfNotExist=true
    hikari:
      poolName: Hikari
      auto-commit: false
    username: admin
    password: admin

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: 'create-drop'
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        ddl:
          auto: update

  zipkin:
    base-url: http://localhost:9411

  eureka:
    fetch-registry: true
    register-with-eureka: true
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
